name: Test Docusaurus Build

on:
  pull_request:
    branches:
      - main # Csak a main branch-be irányuló PR-ek esetén

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build API docs
        run: yarn docusaurus gen-api-docs all
      - name: Build
        run: yarn build